# Generated by Django 5.1.2 on 2024-10-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CONTACT',
            field=models.CharField(max_length=15),
        ),
    ]
