# Generated by Django 5.1.2 on 2024-10-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOOK_TITLE', models.CharField(max_length=100)),
                ('BOOK_AUTHOR', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=100)),
                ('BOOK_CATEGORY', models.CharField(max_length=100)),
                ('BOOK_IMAGE', models.ImageField(null=True, upload_to='outimage/')),
            ],
        ),
    ]
